apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: argocd44
  labels:
    app: web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image:  darkdevil7/argocd:mouse
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: argocd44
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
